apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: HorizontalPodAutoscaler
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 2

images:
  - name: donekaro/chat-api
    newName: donekaro/chat-api
    newTag: local
  - name: donekaro/notification-service
    newName: donekaro/notification-service
    newTag: local
  - name: donekaro/recurring-engine
    newName: donekaro/recurring-engine
    newTag: local
  - name: donekaro/frontend
    newName: donekaro/frontend
    newTag: local
